python train_FKD_parallel.py \
    --wandb-project 'val_rn50_imnet_10' \
    --batch-size 50 \
    --gradient-accumulation-steps 2 \
    --model resnet50 \
    --cos --loss-type "mse_gt" --ce-weight 0.1 \
    -j 4 \
    -T 20 \
    --mix-type 'cutmix' \
    --output-dir ./save/val_rn50_imnet_10/ \
    --train-dir /netscratch/bmoser/sre2l/recover/syn_data/full_r50/ \
    --val-dir /ds-sds/images/imagenet/val/ \
    --fkd-path /netscratch/bmoser/sre2l/relabel/FKD_prism_r50/
